import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Open_Sans } from "next/font/google";

const space = Open_Sans({ subsets: ["latin"], display: "swap" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={space.className}>
      <body className="bg-blue-50">
        <header className="bg-blue-500 text-center py-12 text-white space-y-3 px-4">
          <h1 className="font-bold text-4xl">Pelagic Bird Watching Trips</h1>
          <p className="m-auto max-w-3xl">
            Experience the thrill of observing pelagic birds in their natural
            habitat off the coast of Mangaluru, Karnataka, India
          </p>
        </header>

        <main className="container max-w-5xl py-10 space-y-10">{children}</main>

        <footer className="bg-blue-800 text-white text-center py-10">
          © 2025 Pelagic Bird Watching - Mangaluru | All Rights Reserved
        </footer>
      </body>
    </html>
  );
}